    {
        "lukas-reineke/lsp-format.nvim"
    },
    {
        "ThePrimeagen/git-worktree.nvim"
    },
    {
        "tpope/vim-fugitive"
    },
    {
        "lewis6991/gitsigns.nvim",
        config = true
    },
    {
        "ggandor/leap.nvim"
    },
    {
        "mfussenegger/nvim-lint"
    },
    {
        "neovim/nvim-lspconfig"
    },
    {
        "L3MON4D3/LuaSnip"
    },
    {
        "hrsh7th/nvim-cmp"
    },
    {
        "onsails/lspkind-nvim"
    },
    {
        "numToStr/Comment.nvim"
    },
    {
        "hrsh7th/cmp-nvim-lsp"
    },
    {
        "hrsh7th/cmp-buffer"
    },
    {
        "hrsh7th/cmp-path"
    },
    {
        "saadparwaiz1/cmp_luasnip"
    },
    {
        "hrsh7th/cmp-nvim-lsp-signature-help"
    },
    {
        "hrsh7th/cmp-cmdline"
    },
    {
        "pocco81/true-zen.nvim"
    }
})
